### ISSUE TITLE
'npm run dev' fails on fresh install

### ISSUE THREAD

**Issue by bjmc** [ducksoupdev/vue-webpack-typescript#16]
This is on Ubuntu 16.04. Any suggestions?

    > myproject-web@1.0.0 copy:bs /home/bjmc/Sandbox/myproject/myproject-web
    > ncp node_modules/bootstrap/dist/css/bootstrap.css src/css/bootstrap.css
    
    [0] /home/bjmc/Sandbox/myproject/myproject-web/config/webpack.config.dev.js:15
    [0] webpackConfig.plugins = [...webpackConfig.plugins,
    [0]                          ^^^
    [0] 
    [0] SyntaxError: Unexpected token ...
    [0]     at exports.runInThisContext (vm.js:53:16)
    [0]     at Module._compile (module.js:374:25)
    [0]     at Object.Module._extensions..js (module.js:417:10)
    [0]     at Module.load (module.js:344:32)
    [0]     at Function.Module._load (module.js:301:12)
    [0]     at Module.require (module.js:354:17)
    [0]     at require (internal/module.js:12:17)
    [0]     at Object.<anonymous> (/home/bjmc/Sandbox/myproject/myproject-web/webpack.config.js:1:80)
    [0]     at Module._compile (module.js:410:26)
    [0]     at Object.Module._extensions..js (module.js:417:10)
    [0] webpack-dev-server --hot --inline exited with code 1
    --> Sending SIGTERM to other processes..
    [1] node-sass --watch --output ./src/css ./src/sass exited with code null

    npm ERR! Linux 4.4.0-79-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2
    npm ERR! code ELIFECYCLE
    npm ERR! myproject-web@1.0.0 dev: `cross-env NODE_ENV=development npm run sass && npm run copy:bs && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the myproject-web@1.0.0 dev script 'cross-env NODE_ENV=development npm run sass && npm run copy:bs && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the myproject-web package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     cross-env NODE_ENV=development npm run sass && npm run copy:bs && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs myproject-web
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls myproject-web
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/bjmc/Sandbox/myproject/myproject-web/npm-debug.log

**Comment by bjmc** [comment]
It looks like this is because the "spread" operator (`...`) isn't supported in nodejs 4.X, which is the version installed from the Ubuntu 16.04 repository. Using [a PPA to upgrade to nodejs 6.X](https://github.com/nodesource/distributions) seems to fix the problem.

Maybe worth documenting the minimum nodejs version this template is compatible with?
