### ISSUE TITLE
ts-loader throws error

### ISSUE THREAD

**Issue by oguzhaneren** [ducksoupdev/vue-webpack-typescript#4]
When I run "npm run dev", ts-loader throws error.

> TypeError: Cannot convert undefined or null to object

OS: Windows 10

```

> my-project@1.0.0 dev O:\Dropbox\development\code\tryouts\vuejs\my-project
> cross-env NODE_ENV=development npm run sass && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"


> my-project@1.0.0 sass O:\Dropbox\development\code\tryouts\vuejs\my-project
> node-sass --output ./src/css ./src/sass

Rendering Complete, saving .css file...
Wrote CSS to O:\Dropbox\development\code\tryouts\vuejs\my-project\src\css\main.css
Wrote 1 CSS files to O:\Dropbox\development\code\tryouts\vuejs\my-project\src\css
[0] Project is running at http://localhost:8081/
[0] webpack output is served from /
[0] Content not from webpack is served from ./src
[0] 404s will fallback to /index.html
[0] webpack: wait until bundle finished: /
[0] ts-loader: Using typescript@2.1.6 and O:\Dropbox\development\code\tryouts\vuejs\my-project\tsconfig.json
[0] Hash: aaaeebcc443542d94e3f
[0] Version: webpack 2.2.1
[0] Time: 14217ms
[0]                  Asset      Size  Chunks                    Chunk Names
[0]                main.js    725 kB    0, 1  [emitted]  [big]  main
[0]            main.min.js    281 kB    1, 0  [emitted]  [big]  main.min
[0]            main.js.map    880 kB    0, 1  [emitted]         main
[0]         main.min.js.gz   94.7 kB          [emitted]
[0] ../assets/img/logo.png   6.85 kB          [emitted]
[0]        ../css/main.css  81 bytes          [emitted]
[0] chunk    {0} main.js, main.js.map (main) 686 kB [entry] [rendered]
[0]     [8] ./~/vue/dist/vue.common.js 226 kB {0} {1} [built]
[0]    [45] (webpack)/hot/emitter.js 77 bytes {0} {1} [built]
[0]    [46] ./src/main.ts 677 bytes {0} {1} [built]
[0]    [47] (webpack)-dev-server/client?http://localhost:8081 5.28 kB {0} {1} [built]
[0]    [48] (webpack)/hot/dev-server.js 1.57 kB {0} {1} [built]
[0]   [112] ./~/strip-ansi/index.js 161 bytes {0} {1} [built]
[0]   [114] ./src/components/about/index.ts 146 bytes {0} {1} [built]
[0]   [117] ./src/components/list/index.ts 145 bytes {0} {1} [built]
[0]   [119] ./src/components/navbar/index.ts 147 bytes {0} {1} [built]
[0]   [123] ./~/url/url.js 23.3 kB {0} {1} [built]
[0]   [126] ./~/vue-router/dist/vue-router.common.js 56.1 kB {0} {1} [built]
[0]   [127] (webpack)-dev-server/client/overlay.js 3.6 kB {0} {1} [built]
[0]   [128] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} [built]
[0]   [130] (webpack)/hot/log-apply-result.js 1.02 kB {0} {1} [built]
[0]   [131] multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.ts 52 bytes {0} {1} [built]
[0]      + 117 hidden modules
[0] chunk    {1} main.min.js (main.min) 686 kB [entry] [rendered]
[0]     [8] ./~/vue/dist/vue.common.js 226 kB {0} {1} [built]
[0]    [45] (webpack)/hot/emitter.js 77 bytes {0} {1} [built]
[0]    [46] ./src/main.ts 677 bytes {0} {1} [built]
[0]    [47] (webpack)-dev-server/client?http://localhost:8081 5.28 kB {0} {1} [built]
[0]    [48] (webpack)/hot/dev-server.js 1.57 kB {0} {1} [built]
[0]   [112] ./~/strip-ansi/index.js 161 bytes {0} {1} [built]
[0]   [114] ./src/components/about/index.ts 146 bytes {0} {1} [built]
[0]   [117] ./src/components/list/index.ts 145 bytes {0} {1} [built]
[0]   [119] ./src/components/navbar/index.ts 147 bytes {0} {1} [built]
[0]   [123] ./~/url/url.js 23.3 kB {0} {1} [built]
[0]   [126] ./~/vue-router/dist/vue-router.common.js 56.1 kB {0} {1} [built]
[0]   [127] (webpack)-dev-server/client/overlay.js 3.6 kB {0} {1} [built]
[0]   [128] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} [built]
[0]   [130] (webpack)/hot/log-apply-result.js 1.02 kB {0} {1} [built]
[0]   [131] multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.ts 52 bytes {0} {1} [built]
[0]      + 117 hidden modules
[0] webpack: Compiled successfully.
[0] webpack: Compiling...
[0] webpack: wait until bundle finished: /css/main.css
[0] O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\ts-loader\dist\watch-run.js:15
[0]         Object.keys(watcher.mtimes)
[0]                ^
[0]
[0] TypeError: Cannot convert undefined or null to object
[0]     at Function.keys (native)
[0]     at Compiler.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\ts-loader\dist\watch-run.js:15:16)
[0]     at next (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:140:14)
[0]     at Compiler.Shared.share.compilerInvalid (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack-dev-middleware\lib\Shared.js:144:5)
[0]     at next (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:140:14)
[0]     at Compiler.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\CachePlugin.js:32:5)
[0]     at Compiler.applyPluginsAsyncSeries (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:142:13)
[0]     at Watching._go (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:43:16)
[0]     at Watching.invalidate (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:121:8)
[0]     at Watching.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:106:8)
[0]     at EventEmitter.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\node\NodeWatchFileSystem.js:44:4)
[0]     at EventEmitter.g (events.js:260:16)
[0]     at emitTwo (events.js:87:13)
[0]     at EventEmitter.emit (events.js:172:7)
[0]     at EventEmitter._onTimeout (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\watchpack\lib\watchpack.js:139:7)
[0]     at Timer.listOnTimeout (timers.js:92:15)
[0] webpack-dev-server --hot --inline exited with code 1
--> Sending SIGTERM to other processes..
[1] node-sass --watch --output ./src/css ./src/sass exited with code 1

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ooo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@1.0.0 dev: `cross-env NODE_ENV=development npm run sass && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@1.0.0 dev script 'cross-env NODE_ENV=development npm run sass && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development npm run sass && concurrently --kill-others "webpack-dev-server --hot --inline" "node-sass --watch --output ./src/css ./src/sass"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ooo\AppData\Roaming\npm-cache\_logs\2017-02-22T15_05_30_614Z-debug.log
```

**Comment by ducksoupdev** [comment]
Can you check the log at the end of the output to see if it reports any other details? I have encountered a few issues with ts-loader and have switched successfully to awesome-typescript-loader in a number of projects. Might be worth switching it out to see if works?

**Comment by oguzhaneren** [comment]
There is any no detail in log file.

I changed loaders as  "awesome-typescript-loader" but nothings changed.

Same error:

```
O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\awesome-typescript-loader\src\instance.ts:334
[0]         const changedFiles = Object.keys(mtimes).map(toUnix);
[0]                                     ^
[0] TypeError: Cannot convert undefined or null to object
[0]     at Function.keys (native)
[0]     at Compiler.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\awesome-typescript-loader\src\instance.ts:334:37)
[0]     at next (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:140:14)
[0]     at Compiler.Shared.share.compilerInvalid (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack-dev-middleware\lib\Shared.js:144:5)
[0]     at next (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:140:14)
[0]     at Compiler.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\CachePlugin.js:32:5)
[0]     at Compiler.applyPluginsAsyncSeries (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\tapable\lib\Tapable.js:142:13)
[0]     at Watching._go (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:43:16)
[0]     at Watching.invalidate (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:121:8)
[0]     at Watching.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\Compiler.js:106:8)
[0]     at EventEmitter.<anonymous> (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\webpack\lib\node\NodeWatchFileSystem.js:44:4)
[0]     at EventEmitter.g (events.js:260:16)
[0]     at emitTwo (events.js:87:13)
[0]     at EventEmitter.emit (events.js:172:7)
[0]     at EventEmitter._onTimeout (O:\Dropbox\development\code\tryouts\vuejs\my-project\node_modules\watchpack\lib\watchpack.js:139:7)
[0]     at Timer.listOnTimeout (timers.js:92:15)
[0] webpack-dev-server --hot --inline exited with code 1
--> Sending SIGTERM to other processes..
[1] node-sass --watch --output ./src/css ./src/sass exited with code 1
```

**Comment by ducksoupdev** [comment]
What version of node are you running?

**Comment by kenyk7** [comment]
I have the same error:
node: v6.9.5
npm: 3.10.10

**Comment by ducksoupdev** [comment]
I have tried with both node v6.9.4 and v6.10.0 on Windows 10 and they both build successfully. 

![image](https://cloud.githubusercontent.com/assets/946879/23233923/512e1f00-f948-11e6-9309-e782ffc68ee6.png)

Can you try `npm cache clean` and create a new project using the template?

**Comment by ducksoupdev** [comment]
I found this issue on the ts-loader repo that describes the same issue - https://github.com/TypeStrong/ts-loader/issues/479. Can you try the solution and see if it works?

**Comment by oguzhaneren** [comment]
I updated npm (to v6.9.5) and created new project, its works :)
